### PR TITLE
connectionTimeout input value is in seconds, while jedis expects millisecs

### PR DESCRIPTION
**Pull request by lingma**
connectionTimeout input value is in seconds, while jedis expects milliseconds, a multiplication of 1000 is necessary.

### CODE REVIEW

**Comment by lingma** [comment]
after the modification in the 3 files, I suppose line 45 and  51 of RedisTargetConfig.java in com.streamsets.pipeline.stage.destination.redis should be modified to 60 instead of 1000. I am not aware of the purpose here, so I did not modify, at least 1000 is not a big issue

**Comment by jarcec** [comment]
Thank you for the contribution @lingma ! Since you're fixing the units in target, do you mind doing that in the origin and lookup as well?

In order for me I need to ask you to [docu-sign our contribution agreement](https://streamsets.com/contributing/) and if you don't mind please also create user account on our [JIRA server](https://issues.streamsets.com/browse/SDC-5659) so that I can assign the JIRA to you and give you proper contribution :)

**Comment by lingma** [comment]
JIRA user lingma has been created, I have fixed lookup part yesterday, I will check again to make sure that everything will be fixed. Thanks. The agreement has been signed yesterday either.

**Comment by jarcec** [comment]
Ah, you're right - all three components have been addressed by this. Sorry I have missed that.

Let me run your contribution by our test automation and I'll merge if it succeeds :)

**Comment by lingma** [comment]
I found some other files under your suggestion, and they have also been fixed with new update. Please also check them, thanks.

**Comment by jarcec** [comment]
Thank you for your contribution @lingma - I just merged it to master branch!

**Pull request closed without merging**
