### PR TITLE
ANS-16. Add option to CDC config TAB to pass unsupported parameter as string instead of throw exception

### PR DESCRIPTION
**Pull request by estatic**
These changes allows to pass unsupported data type as string without throwing exceptions.

### CODE REVIEW

**Comment by harishreedharan** [comment]
We already added this functionality in master and SDC 3.0. Does it not work for you?

https://github.com/streamsets/datacollector/blob/master/jdbc-lib/src/main/java/com/streamsets/pipeline/stage/origin/jdbc/cdc/oracle/OracleCDCSource.java#L683

**Comment by estatic** [comment]
Hi @harishreedharan,
 
yes, you are right, I've made changes based on 2.7 version. Seems, my changes doesn't need any more.

**Comment by harishreedharan** [comment]
Let me know how 3.0 works for you with respect to this feature.

**Comment by estatic** [comment]
@harishreedharan Yes, this works as we've expected. Thanks a lot!

**Pull request closed without merging**
