### PR TITLE
SDC-5244. Elasticsearch _parent indexing

### PR DESCRIPTION
**Pull request by marija17**
Adds parentID and routingID to Elasticsearch target.

### CODE REVIEW

**Comment by jrnt30** [comment]
The use case is outlined https://issues.streamsets.com/browse/SDC-5244. 

What can we do to move this along?  Is this something that can be considered for a release? 

We currently have a fairly manual process to patch our DPM deployment to allow us to retain this functionality.

**Comment by jeff303** [comment]
Thank you for the contribution, and sorry for the delay.  I am working on getting this through the internal review process now, and we can target the 2.7.0.0 release for it.

**Comment by jeff303** [comment]
@jrnt30 , @marija17 , this has been merged into master and should be available in the next nightly build, if you want to try it out there.  The target release version is 2.7.0.0.

**Comment by jrnt30** [comment]
Thanks for taking a look! Appreciate your time and the product

**Comment by jarcec** [comment]
Since @jeff303 already merged this, I'll go ahead and close the pull request.

**Pull request closed without merging**
