### PR TITLE
Copy Rabbit headers in as StreamSets headers

### PR DESCRIPTION
**Pull request by brockn**
Straightforward patch. Adds test which relies on mocked components like the other tests.

### CODE REVIEW

**Comment by brockn** [comment]
Tested this in the real world. Working for me.

**Comment by jarcec** [comment]
+1 Seems reasonable to me.

**Comment by jarcec** [comment]
Created JIRA for this one:

https://issues.streamsets.com/browse/SDC-6682

**Comment by jarcec** [comment]
Merged!

**Pull request closed without merging**
