### PR TITLE
fix bug when logdir exist subdirs or livefile to be moved,deleted

### PR DESCRIPTION
**Pull request by sumpan**

### CODE REVIEW

**Comment by kunickiaj** [comment]
Thanks for the contribution! We'll review this shortly.

Meanwhile, have you already signed a CLA?
https://streamsets.com/contributing/

**Comment by sumpan** [comment]
@kunickiaj sure,signed

**Comment by jarcec** [comment]
Would you mind helping me understand on which conditions the issue occurs @sumpan ? Perhaps a small unit test would help in this case.

**Comment by jarcec** [comment]
I wonder if you have seen my feedback @sumpan ?

**Comment by jarcec** [comment]
There hasn't been any update since late August, so I'll go ahead and close this one for now. Please don't hesitate and reopen or submit a new one if needed!

**Pull request closed without merging**
