### PR TITLE
Fix issues SDC-7902 and SDC-7861. Also, change apache-rat check start principle.

### PR DESCRIPTION
**Pull request by estatic**
I've tried to build it on my Macbook and found that there are some issues with tests. So, I've create bug report on JIRA and fixed found issues by these commits.
bug SDC-7902 and SDC-7861

Also, I've removed ANT script which generates bash script and change it with exec goal. It allows to build and test on non-UNIX OSes.

### CODE REVIEW

**Comment by estatic** [comment]
Hi @jarcec!

Well, I think I can do that, but main problem is my macbook has die few
hours ago:(, with all data on it! so, once I fix it or buy new one I can
divide this pull request to several. Cheers!

21 дек. 2017 г. 7:37 PM пользователь "Jarek Jarcec Cecho" <
notifications@github.com> написал:

*@jarcec* requested changes on this pull request.

Do you mind breaking the one pull request into independent requests for
each JIRA/task?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/streamsets/datacollector/pull/42#pullrequestreview-85116026>,
or mute the thread

**Comment by jarcec** [comment]
No worries and take your time @estatic ! Hope that your laptop will be resurrected soon :)

**Comment by estatic** [comment]
Okay, move SDC-7861 issue to another pull request.
https://github.com/streamsets/datacollector/pull/49

**Comment by estatic** [comment]
Moved SDC-7902 to https://github.com/streamsets/datacollector/pull/50

**Comment by estatic** [comment]
Moved OS depended script generation fix to here https://github.com/streamsets/datacollector/pull/51

**Comment by estatic** [comment]
@jarcec Should I close this pull request?

**Comment by jarcec** [comment]
Yup let me do that @estatic .

**Pull request closed without merging**
