### PR TITLE
SDC-12695 Extract timestamp and timestamp type in Kafka Multitopic Consumer

### PR DESCRIPTION
**Pull request by tinawenqiao**
In Kafka Consumer, we can get record timestamp and timestamp type if set Include Timestamps property to true. But not yet in Kafka Multitopic Consumer.

### CODE REVIEW

**Comment by metadaddy** [comment]
Merged as da80d398e073d8e4c39f0d0dec3ddc2b4c0a2ccb

**Comment by jarcec** [comment]
The patch has been merged by @metadaddy , so I'm closing the pull request.

**Comment by metadaddy** [comment]
Thanks for your contribution, @tinawenqiao! This change was merged into the StreamSets Data Collector source today and will appear in version 3.15.0.

**Comment by tinawenqiao** [comment]
@metadaddy It's my honor. This is my first time to contribute code to SDC.

**Pull request closed without merging**
