### PR TITLE
Use groupId for sample sources in archetype

### PR DESCRIPTION
**Pull request by cooper6581**
I don't know enough about maven to know if `${packageInPathFormat}` is preferred.

### CODE REVIEW

**Comment by kiritbasu** [comment]
hi @cooper6581, thanks much for your contributions. Before we accept it could you please sign our CLA.
http://streamsets.com/contributing/
Thanks
Kirit

**Comment by jarcec** [comment]
I'm excited to see people contributing to DataCollector, thank you very much @cooper6581! As Kirit mentioned, we will need you to [fill in ICLA form](https://streamsets.com/contributing/) before we can accept the contribution. Please do not hesitate and let me know if you have any further questions, I'm happy to help!

**Comment by jarcec** [comment]
Please do let me know if you intend to get the contribution in @cooper6581. Otherwise I'll go ahead and close it.

**Comment by cooper6581** [comment]
Thanks for your help @jarcec.  I don't think my legal department is going to get back to me any time soon.  Closing PR.  Thanks for your help!

**Pull request closed without merging**
