### PR TITLE
SDC 8553 Allow Time EL for 'Resource URL' in HTTP processor

### PR DESCRIPTION
**Pull request by tan31989**
This commit is for the improvement feature requested on https://issues.streamsets.com/browse/SDC-8553.

### CODE REVIEW

**Comment by jarcec** [comment]
Thanks for the contribution @tan31989! Would it be feasible to write a unit test for the change to validate that the ELs will indeed work properly?

**Comment by tan31989** [comment]
Hi, @jarcec thanks for the update. I looked into the code and there isn't any tests for `HttpClientCommon.java`. Adding it should be alright, but was wondering, about should I mock `resourceEval` variable? because its initialization is done in another method.

Do you have any other unit test for the above scenario which I can take in as a reference?

Regards,
Nagaraj

**Comment by jarcec** [comment]
I believe that tests for the HTTP Processor are written here @tan31989 

https://github.com/streamsets/datacollector/blob/master/basic-lib/src/test/java/com/streamsets/pipeline/stage/processor/http/HttpProcessorIT.java

**Comment by tan31989** [comment]
@jarcec These tests are for Integration Tests and @dimaspivak mentioned in the slack channel support that:

>We actually are in the process of transitioning our integration and end-to-end functional tests out of the Java unit test harness and into a Python one that we built on top of our StreamSets SDK

Thus after I wrote it, I could not run that test. Running the above tests was not something I know off. You think I can test that individually?

Regards,
Nagaraj

**Comment by jarcec** [comment]
At this point I will ask you to enhance the HttpProcessorIT, we will transition those tests to the engine that @dimaspivak  mentioned later @tan31989 .

**Comment by tan31989** [comment]
@jarcec Yes sure, I have done that and can do that. Could you let me know how I can execute one that file? Any documentation which I can look up?

**Comment by jarcec** [comment]
All test files ending with "IT" are executed through maven failsafe plugin @tan31989 . I believe that you can instruct the plugin to run only given test with` -Dit.test="HttpProcessorIT"`

**Comment by tan31989** [comment]
@jarcec Have added a Integration test in there. Let me know if that suffices for the use case here.

**Comment by jarcec** [comment]
Have you signed our contributor agreement @tan31989 ? I'm having troubles to locate your CLA on our side.

https://streamsets.com/contributing/

**Comment by metadaddy** [comment]
I can confirm that Media iQ have signed the CCLA, @jarcec

**Comment by jarcec** [comment]
Thanks for the validation @metadaddy !

Running the new test on our side seems to fail with:

```
org.junit.ComparisonFailure: expected:<2018010[2]> but was:<2018010[1]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.streamsets.pipeline.stage.processor.http.HttpProcessorIT.testHttpGetTimeEl(HttpProcessorIT.java:1039)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

Almost seem like some sort of a timezone issue perhaps @tan31989 ?

**Comment by metadaddy** [comment]
Daylight savings time???

**Comment by tan31989** [comment]
@jarcec have fixed the test case which was missing a timezone. Now have verified this with other timezone, it works.

**Comment by jarcec** [comment]
Thanks, @tan31989 , let me run the updated patch through our CI system and merge it if it succeeds. Do you have an account on our JIRA by any chance? I would like to assign the JIRA to you so that you get recognition for contributing the fix :)

**Comment by tan31989** [comment]
Thanks @jarcec , I'm on Jira and have commented on that issue: https://issues.streamsets.com/browse/SDC-8553

Happy to help with this.

**Comment by jarcec** [comment]
Thanks @tan31989 , I've assigned the JIRA to you then.

**Comment by jarcec** [comment]
Merged, thank you very much for your contribution @tan31989 !

**Pull request closed without merging**
