### PR TITLE
Updated way document keys are set for Couchbase Destination

### PR DESCRIPTION
**Pull request by nicholasc69**
Changed the way document keys are set to a more standard way of setting values in Streamsets. Users can now use the expression language to set custom documents keys to fit more in line to document design models for Couchbase applications.

### CODE REVIEW

**Comment by jarcec** [comment]
Do you mind holding off on the contribution @nicholasc69 ? One of our SEs is actually working on Couchbase lookup processor and as part of that work, he is refactoring the destination as well to reuse a lot of code.

**Comment by nicholasc69** [comment]
Not a problem. Please send my regards to Dean ;-)

**Comment by jarcec** [comment]
The refactoring that I mentioned early on has been merged :)

**Comment by jarcec** [comment]
I will resolve the pull request for now, feel free to reopen though @nicholasc69 if you will have time to rebase the change :)

**Pull request closed without merging**
