### PR TITLE
SDC-2076. Added withCredentials to cluster builder in getCluster method.

### PR DESCRIPTION
**Pull request by jvorhauer**
To fix SDC-2076 just one line of code (actually: one method call to the cluster builder) was needed.
I have tested this with a three node DSE 4.7.5 cluster with authentication set to PasswordAuthentication.

### CODE REVIEW

**Comment by jvorhauer** [comment]
Can't sign the  Contributor License Agreement, cause the link is 404... Can I contribute this Pull request anyway?

**Comment by kiritbasu** [comment]
Hi, Thank you for your submission. Here is the link to the CLA.
http://streamsets.com/contributing/
Thanks
Kirit

**Comment by brockn** [comment]
Looks like @kunickiaj should review.

**Comment by kunickiaj** [comment]
Merged to master and 1.1.x

**Pull request closed without merging**
